### ISSUE TITLE
Support for custom git trailers on the commit message

### ISSUE THREAD

**Issue by twk3** [dropseed/deps#26]
Just like the MR labels setting is useful, git trailers can also be a way of getting important structured information for other automation. 

It would be ideal to be able to add a list of static trailers in the deps settings.

Most typical trailers wouldn't apply unless we also added gotemplating, as they are contextual to the change. (See some typical examples of trailers here: https://git.wiki.kernel.org/index.php/CommitMessageConventions )

But some do make sense even with just a static list. For example, in GitLab there is an automated changelog feature that uses the `Changelog:` trailer to flag a commit for inclusion: https://docs.gitlab.com/ee/api/repositories.html#generate-changelog-data

So in that case it would be ideal to be able to set deps to add a custom trailer so we could add something like `Changelog: updated` to the deps commits.

**Comment by davegaeddert** [comment]
Hey @twk3! I'm actually thinking that a gotemplating solution might make sense here. That allows for some other things that have been requested like a prefix/suffix on the subject line and may open us up to more of the "contextual" content down the road. It's pretty easy to use and means we don't have to add a bunch of different settings for each of those use cases.

Thoughts?

https://github.com/dropseed/deps/pull/27
https://deploy-preview-27--deps-docs.netlify.app/config/#customizing-commit-messages

**Comment by davegaeddert** [comment]
Moving forward with this... here is an example of how it works for this use case:

```yaml
version: 3
dependencies:
- type: js
  settings:
    commit_message_template: |-
      {{.SubjectAndBody}}

      Changelog: updated
```

**Comment by twk3** [comment]
Thanks @davegaeddert 

This is working in my test pipelines, and we will start using it in our regular pipeline shortly.

**Comment by davegaeddert** [comment]
Sounds good. Putting the final link here for others: https://www.dependencies.io/config/#customizing-commit-messages
