### ISSUE TITLE
`deps upgrade` exit with status 129 in WSL

### ISSUE THREAD

**Issue by Sese-Schneider** [dropseed/deps#29]
I'm trying to run `deps upgrade` in WSL (Windows Subsystem for Linux), but the command fails with:

```
panic: exit status 129
```

A verbose run provides no more information.

<details>
<summary>Full Error Log</summary>

```
$ deps upgrade
panic: exit status 129

github.com/dropseed/deps/internal/git.HasStagedChanges(0x2)
        /home/runner/work/deps/deps/internal/git/main.go:274 +0x137
github.com/dropseed/deps/internal/runner.Local(0x0, 0x0)
        /home/runner/work/deps/deps/internal/runner/local.go:16 +0x34
main.glob..func8(0xb8ad80, 0xbbf5b0, 0x0, 0x0)
        /home/runner/work/deps/deps/cmd/deps/upgrade.go:13 +0x25
github.com/spf13/cobra.(*Command).execute(0xb8ad80, 0xbbf5b0, 0x0, 0x0, 0xb8ad80, 0xbbf5b0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb8a600, 0x0, 0xb4d780, 0xc0000a2058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/runner/work/deps/deps/cmd/deps/main.go:15 +0x2d
```

</details>

**Comment by davegaeddert** [comment]
Hey @Sese-Schneider! Unfortunately I don't have a good way to reproduce this. It looks like the error would have come from this command:
https://github.com/dropseed/deps/blob/55dd50d91aa2bf4e4301ccb0b098920e0cfc4f6b/internal/git/main.go#L271

Do you know of any reason `git diff --name-only --staged` wouldn't have worked? Does that git command work if you run it yourself in the same directory you were in?

**Comment by Sese-Schneider** [comment]
@davegaeddert You were right, the `git` command wasn't working properly in the repo I was in.
So the issue I experienced was unrelated.
Thanks for your help.
